# Generated by Django 2.2 on 2021-03-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=150)),
                ('slide_img', models.ImageField(upload_to='uploads/slider')),
                ('slide_slug', models.SlugField()),
                ('title_on_slide', models.CharField(blank=True, max_length=250, null=True)),
                ('desc_on_slide', models.TextField(blank=True, max_length=500, null=True)),
                ('call_to_action_link_on_slide', models.CharField(blank=True, max_length=250, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'carousel_slides',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(to='carousel.CarouselSlide')),
            ],
            options={
                'db_table': 'carousel',
            },
        ),
    ]
