# Generated by Django 2.2 on 2021-03-12 13:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20210310_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
